"""Initial migration

Revision ID: ba8fde62be28
Revises: 
Create Date: 2026-06-25 07:00:48.970358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8fde62be28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('md5_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('md5_hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('sha256_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('sha256_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sha256_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('sha256_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('md5_hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('md5_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
